language: python
sudo: false
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip

python:
 - "3.4"
 - "3.5"
 - "3.6"
 - "3.7"

env:
 - DJANGO="Django>=1.7,<1.8"
 - DJANGO="Django>=1.8,<1.9"
 - DJANGO="Django>=1.9,<1.10"
 - DJANGO="Django>=1.10,<1.11"
 - DJANGO="Django>=1.11,<2.0"
 - DJANGO="Django>=2.0,<2.1"
 - DJANGO="Django>=2.1,<2.2"

install:
 - pip install $DJANGO
 - pip install -e .

script: "./runtests.sh"

matrix:
  exclude:

    - python: "3.4"
      env: DJANGO="Django>=2.1,<2.2"

    - python: "3.5"
      env: DJANGO="Django>=1.7,<1.8"

    - python: "3.6"
      env: DJANGO="Django>=1.7,<1.8"

    - python: "3.6"
      env: DJANGO="Django>=1.8,<1.9"

    - python: "3.6"
      env: DJANGO="Django>=1.9,<1.10"

    - python: "3.6"
      env: DJANGO="Django>=1.10,<1.11"

    - python: "3.7"
      env: DJANGO="Django>=1.7,<1.8"

    - python: "3.7"
      env: DJANGO="Django>=1.8,<1.9"

    - python: "3.7"
      env: DJANGO="Django>=1.9,<1.10"

    - python: "3.7"
      env: DJANGO="Django>=1.10,<1.11"

    - python: "3.7"
      env: DJANGO="Django>=1.11,<2.0"
